### ISSUE TITLE
Running tests failed with "Error: No active group"

### ISSUE THREAD

**Issue by AlvinLaiPro** [testing-library/user-event#1082]
### Reproduction example

cannot be reproduced by codesandbox

### Prerequisites

As I researched the root cause of this error, I would like to report it without reproduction steps.

In the 14.x version of User-event, [this line ](https://github.com/testing-library/user-event/blob/1aa2027e5ec445ab413808556efa7763b65053d3/src/utils/dataTransfer/Clipboard.ts#L220) of the `Clipboard.ts` file will cause Jasmine to install an `afterAll` hook unexpectedly. When a normal test suite is completed, Jasmine will try to call this callback without an active group.

### Expected behavior

Tests run without errors.

### Actual behavior

Test suite failed to run

    Error: No active group

      at JasmineAllureReporter.get currentGroup [as currentGroup] (node_modules/allure-jasmine/src/JasmineAllureReporter.ts:50:38)
      at node_modules/allure-jasmine/src/JasmineAllureReporter.ts:250:54
      at Object.<anonymous> (node_modules/allure-jasmine/src/JasmineAllureReporter.ts:220:40)

### User-event version

14.4.3

### Environment

Testing Library framework: 

JS framework: 

Test environment: 

DOM implementation: 

### Additional context

Only failed with using `allure-jasmine` to generate reports.

**Comment by AlvinLaiPro** [comment]
It might be more helpful with a code example.
[minimal-demo.zip](https://github.com/testing-library/user-event/files/10183792/minimal-demo.zip)

**Comment by ph-fritsche** [comment]
Shouldn't this be an issue with `allure-jasmine` ?
In test runners that provide a fresh context for every suite it doesn't matter if we restore the original Clipboard. But if test suites run in a shared context, we want to make it easier to use this library without side-effects leaking from the test suite it was imported in. So if there is an `afterAll` hook, we call it so the user doesn't have to set this up in every suite.
The concept of `afterAll` being a hook in test environments and working like that is so common that this is the first time I hear of a conflict with another use of a global `afterAll` function.

We could provide a `pure` export like `react-testing-library` does.
