### ISSUE TITLE
Change events on `<select>` throws `Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.`

### ISSUE THREAD

**Issue by charlie-bud** [testing-library/user-event#1113]
### Reproduction example

https://codesandbox.io/s/peaceful-noyce-sktjvt?file=/src/App.test.js

### Prerequisites

1. 'Get' a combobox element (`screen.getByRole("combobox", { name: /test select/i })`).
2. 'Get' an option element (`screen.getByRole("option", { name: /test option/i })`).
3. Use these elements in `userEvent.selectOptions(select, option)` or `fireEvent.change(select, { target: { value: "test-value" } })`.

### Expected behavior

Value of the select element will change to the selected option.

### Actual behavior

The following error is thrown:

```
 TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.

      at Object.exports.convert (node_modules/jsdom/lib/jsdom/living/generated/Event.js:22:9)
      at Proxy.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:236:24)
      at node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:43
      at node_modules/@testing-library/react/dist/pure.js:66:16
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at Object.eventWrapper (node_modules/@testing-library/react/dist/pure.js:65:28)
      at Object.wrapEvent (node_modules/@testing-library/user-event/dist/cjs/event/wrapEvent.js:8:28)
      at Object.dispatchEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:22)
      at Object.dispatchUIEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:24:26)
      at selectOption (node_modules/@testing-library/user-event/dist/cjs/utility/selectOptions.js:62:14)
      at Object.selectOptionsBase (node_modules/@testing-library/user-event/dist/cjs/utility/selectOptions.js:98:13)
      at async /Users/test/repos/some-app/node_modules/@testing-library/react/dist/pure.js:59:16
```

### User-event version

14.4.3

### Environment

This bug cannot be reproduced in the CodeSandbox environment. However, here is more info about our packages:

```
{
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=8.0.0"
  },
  "dependencies": {
    "@babel/runtime": "^7.21.0",
    "@babel/runtime-corejs3": "^7.21.0",
    "@tanstack/react-query": "^4.26.1",
    "@tanstack/react-query-devtools": "^4.28.0",
    "core-js": "^3.29.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.9.0",
    "source-map-support": "^0.5.21",
  },
  "devDependencies": {
    "@babel/core": "^7.21.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^29.4.0",
    "@types/react": "^17.0.53",
    "@types/react-dom": "^17.0.19",
    "babel-loader": "^9.1.2",
    "copy-webpack-plugin": "^11.0.0",
    "husky": "^8.0.3",
    "jest": "^29.5.0",
    "jest-environment-jsdom": "^29.5.0",
    "msw": "^1.1.0",
    "nodemon": "^2.0.21",
    "typescript": "^4.9.5",
    "webpack": "^5.76.0",
    "webpack-cli": "^5.0.1",
    "webpack-node-externals": "^3.0.0"
  }
}
```

### Additional context

Other events such as `userEvent.type` work fine. The same issue could be replicated by using `fireEvent.change` on the same select element.

**Comment by ouya99** [comment]
any update on this matter? or workaround

**Comment by charlie-bud** [comment]
@ouya99 This issue turns out to be caused by a private package we implement which was using an old `event-target-polyfill`. Gone are the days of needing to support IE11 anymore, we resolved this issue by scrapping the polyfill 👍
