### ISSUE TITLE
activeElement might change during userEvent.type causing runtime errors

### ISSUE THREAD

**Issue by beckerei** [testing-library/user-event#356]
- `@testing-library/user-event` version: >= 11.1.0
- `@testing-library/dom` version: 5.10.1
- Testing Framework and version: jest@26.0.1
- DOM Environment: jsdom jest-environment-jsdom-global@2.0.2
- node: 13.7.0

### What you did:

Using `userEvent.type`. We have like > 1k tests which mostly use `fireEvent` but slowly upgrading to `userEvent`. All run fine, execept for one I encountered while updating our dependencies.

As a tmp fix one can use `fireEvent.change`.

### What happened:
I narrowed it down to start with the release of https://github.com/testing-library/user-event/releases/tag/v11.1.0
```
    TypeError: Cannot read property 'length' of undefined

      at calculateNewValue (node_modules/@testing-library/user-event/dist/type.js:312:43)
      at typeCharacter (node_modules/@testing-library/user-event/dist/type.js:366:43)
      at typeImpl (node_modules/@testing-library/user-event/dist/type.js:230:29)
      at node_modules/@testing-library/user-event/dist/type.js:20:14
      at node_modules/@testing-library/react/dist/pure.js:58:16
```
### Problem description:
We currently have 90 occurrences for `await userEvent.type(` in our codebase, yet only a single one has this issue. I don't understand (yet) what could cause this.
But I figured out the `activeElement` is always the body, so calling `currentValue()` will be undefined, as `body` has no value prop.

I will provide more details if I find more.

**Comment by tsmithATX** [comment]
I'm seeing this happen with portals where the portal component opens and has an active element but once you try to focus back to a text area to type the activeElement is the root of the portal.

**Comment by tsmithATX** [comment]
v12.0.14 addressed our issues, no longer seeing this happen!

**Comment by Junhao6503** [comment]
I am still encountering this issue due to portals. It gives me errors like:
```
TypeError: Cannot read property 'length' of undefined
      at setSelectionRange (node_modules/@testing-library/user-event/dist/type.js:240:70)
      at fireInputEventIfNeeded (node_modules/@testing-library/user-event/dist/type.js:269:5)
      at handleDel (node_modules/@testing-library/user-event/dist/type.js:613:5)
      at node_modules/@testing-library/user-event/dist/type.js:144:29
      at typeImpl (node_modules/@testing-library/user-event/dist/type.js:159:4)
      at type (node_modules/@testing-library/user-event/dist/type.js:73:14)
      at Object.clear (node_modules/@testing-library/user-event/dist/clear.js:26:18)
      at Object.<anonymous> (src/__tests__/UserProfile/UserProfileEdit.test.js:148:17)
```
