### ISSUE TITLE
userEvent.type renders the following error: ReferenceError: HTMLInputElement is not defined 

### ISSUE THREAD

**Issue by rey-wright** [testing-library/user-event#434]
- `@testing-library/user-event` version: `"^12.1.2"`
- Testing Framework and version: `mocha: "^6.0.2"`
  
- DOM Environment: `jsdom: "^15.2.1"`

Relevant code or config

```javascript
import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

describe('input', () => {
  it('accepts user typing', async () => {
    render(<input type="text" aria-label="blah" name="name" />);
    const input = screen.getByLabelText('blah');
    // same thing for the following: 
    // const input = screen.getByRole("textbox");
    await userEvent.type(input, 'Hello,{enter}World!');
  });
});

```

What you did: Tried to use userEvent.type

What happened: Following error triggered:  `ReferenceError: HTMLInputElement is not defined`

```sh
1) input
       accepts user typing:
     ReferenceError: HTMLInputElement is not defined
      at isClickable (node_modules/@testing-library/user-event/dist/utils.js:236:61)
      at fireInputEventIfNeeded (node_modules/@testing-library/user-event/dist/type.js:252:61)
      at typeCharacter (node_modules/@testing-library/user-event/dist/type.js:323:26)
      at callback (node_modules/@testing-library/user-event/dist/type.js:216:26)
      at /Users/billy/repos/projectrepo/node_modules/@testing-library/user-event/dist/type.js:144:29
      at typeImpl (node_modules/@testing-library/user-event/dist/type.js:159:4)
      at Object.type (node_modules/@testing-library/user-event/dist/type.js:73:14)
      at _callee$ (src/client/modules/top-search/components/DecoratedNumericInputGroup/__test__/DecoratedNumericInputGroup.spec.js:10:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (src/client/modules/top-search/components/DecoratedNumericInputGroup/__test__/DecoratedNumericInputGroup.spec.js:21:103)
      at _next (src/client/modules/top-search/components/DecoratedNumericInputGroup/__test__/DecoratedNumericInputGroup.spec.js:23:194)
      at /Users/billy/repos/projectrepo/src/client/modules/top-search/components/DecoratedNumericInputGroup/__test__/DecoratedNumericInputGroup.spec.js:23:364
      at new Promise (<anonymous>)
      at Context.<anonymous> (src/client/modules/top-search/components/DecoratedNumericInputGroup/__test__/DecoratedNumericInputGroup.spec.js:23:97)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by kentcdodds** [comment]
Thanks! I think that the fix would be here:

https://github.com/testing-library/user-event/blob/ba086e421485b9796caeb72fdbc9a4901efff1da/src/utils.js#L251

That should probably be:

```
(element instanceof element.ownerDocument.defaultView.HTMLInputElement &&
```

**Comment by kentcdodds** [comment]
Actually, there are several global references in that file that should probably be changed. Anywhere `document` is used, should do `element.ownerDocument` instead. If anyone want to fix this, please feel free!

**Comment by reywright** [comment]
@kentcdodds thanks for the quick feedback, you're a boss. I created the PR as you so kindly specified.
