### ISSUE TITLE
userEvent.type generating jsdom Error: Not implemented: navigation from

### ISSUE THREAD

**Issue by astrotim** [testing-library/user-event#610]
- `@testing-library/user-event` version: 12.8.3

- Testing Framework and version: Jest 26.1.0
  
- DOM Environment: jsdom 16.4.0
  

Relevant code or config

```javascript
it(`supports arrow key navigation`, async () => {
  render(<Component />);

  const moreButton = screen. getByTestId('More');
  const navItem = screen.getByText('Nav Item Text');

  // focus, then press space on the "More" button
  moreButton.focus();
  expect(moreButton).toHaveFocus();
  userEvent.type(moreButton, '{space}');

  // move from the "More" button to first item
  userEvent.type(moreButton, '{arrowdown}');
  await waitFor(() => expect(navItem).toHaveFocus());

  // then back up again
  userEvent.type(navItem, '{arrowup}');
  await waitFor(() => expect(moreButton).toHaveFocus());
});
```

What you did:

Refactored 

```js
fireEvent.keyDown(element, { key: 'ArrowUp', code: 'ArrowUp' });
```

to 

```js
userEvent.type(element, '{arrowup}');
```

What happened:

Tests still pass, but now a console.error is reported as follows:

```
● Console

console.error
  Error: Not implemented: navigation (except hash changes)
      at module.exports (path/to/project/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
      at navigateFetch (path/to/project/node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
      at exports.navigate (path/to/project/node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
      at Timeout._onTimeout (path/to/project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js:81:7)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7) undefined

  at VirtualConsole.<anonymous> (../../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
  at module.exports (../../node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
  at navigateFetch (../../node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
  at exports.navigate (../../node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
  at Timeout._onTimeout (../../node_modules/jsdom/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js:81:7)
```

**Comment by ph-fritsche** [comment]
Sounds like your `Component` has an event handler on another KeyEvent (probably `keyup`) that uses `window.navigate` which is not implemented in jsdom.
`userEvent` does not use `window.navigate` anywhere.

**Comment by astrotim** [comment]
It only has `keydown`, but it also has some of the focus logic wrapped in a `setTimeout` which I'm wondering if it's relevant to the `processTimers` call in the stack trace. If I remove the setTimeout, the tests fail, so for now I've just reverted back to `fireEvent` until the component can be refactored (it's very old)
