### ISSUE TITLE
range.selectNodeContents is not a function (v13.0.11+)

### ISSUE THREAD

**Issue by jarretmoses** [testing-library/user-event#641]
- `@testing-library/user-event` version: 13.0.11 -> 13.1.1

- Testing Framework and version: `jest: 26.6.0`
  
- DOM Environment: `"@testing-library/jest-dom": "5.11.10"`
  

Relevant code or config standard CRA config with the following in my `package.json

```javascript
  "jest": {
    "resetMocks": false,
    "clearMocks": true
  }
```

What you did: I upgraded to the most recent version of @testing-library/user-event and the error started to appear. I stepped through release versions and isolated the issue started at `v13.0.11`

What happened: The following error started to appear 

```
TypeError: range.selectNodeContents is not a function
        at setSelectionRange (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/utils/edit/selectionRange.js:86:9)
        at setSelectionRangeAfterInputHandler (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/shared/fireInputEvent.js:57:34)
        at fireInputEvent (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/shared/fireInputEvent.js:34:3)
        at Object.handle (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/plugins/character.js:167:32)
        at applyPlugins (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/keyboardImplementation.js:137:12)
        at keypress (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/keyboardImplementation.js:115:5)
        at keyboardImplementation (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/keyboardImplementation.js:47:9)
        at keyboardImplementation (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/keyboardImplementation.js:61:12)
        at keyboardImplementation (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/keyboardImplementation.js:61:12)
        at keyboardImplementationWrapper (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/keyboard/index.js:55:65)
        at typeImplementation (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/type/typeImplementation.js:49:51)
        at Object.type (/Users/jarretmoses/Dev/web/node_modules/@testing-library/user-event/dist/type/index.js:27:60)
        at Object.<anonymous> (/Users/jarretmoses/Dev/web/src/v2/components/__tests__/register-listing/landlord-referral.component.test.tsx:388:15)
        at _callCircusTest (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/run.js:212:5)
        at _runTest (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/run.js:149:3)
        at _runTestsForDescribeBlock (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/run.js:63:9)
        at _runTestsForDescribeBlock (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/run.js:57:9)
        at run (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/run.js:25:3)
        at runAndTransformResultsToJestFormat (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
        at jestAdapter (/Users/jarretmoses/Dev/web/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
        at runTestInternal (/Users/jarretmoses/Dev/web/node_modules/jest-runner/build/runTest.js:380:16)
        at runTest (/Users/jarretmoses/Dev/web/node_modules/jest-runner/build/runTest.js:472:34)
        at Object.worker (/Users/jarretmoses/Dev/web/node_modules/jest-runner/build/testWorker.js:133:12)
```

Reproduction repository: (ill work on one)

Problem description: 

Suggested solution:

**Comment by jarretmoses** [comment]
Closing until some more investigation I am starting to realize this may be getting triggered due to another library.

**Comment by kyleBeikirch** [comment]
@jarretmoses I also had this issue when upgrading to the latest version. I haven't dug fully into this as to why, but in my jest setup file, I have this shim that has been needed in the past.
```
window.document.createRange = () => ({
    setStart: () => {},
    setEnd: () => {},
    // @ts-ignore
    commonAncestorContainer: {
      nodeName: 'BODY',
      ownerDocument: document
    }
  })
```
This seems to be no longer needed with the latest version and when I remove this shim, the tests still pass without the error.
