### ISSUE TITLE
Using `userEvent.keyboard('{esc}')` throws error

### ISSUE THREAD

**Issue by mancristiana** [testing-library/user-event#689]
- `@testing-library/user-event` version: **13.1.9**
- Testing Framework and version: **jest@26.6.3**
- DOM Environment: jsdom@16.5.3

Relevant code or config

I am trying to test that when I press the Escape key the calendar dialog  in DateInput closes.
```javascript
 it('should close calendar when pressing escape key', () => {
    render(
      <DateInput />
    );
    userEvent.click(screen.getByRole('button', { name: /choose date/i }));
    expect(screen.getByRole('dialog')).toBeInTheDocument();
    userEvent.keyboard('{esc}');
    expect(screen.queryByRole('dialog')).toBeNull();
    expect(screen.getByRole('button', { name: /choose date/i })).toHaveFocus();
  });

```

What happened:

The tests pass, however, I get the following error message in the console.

Error message
```
console.error
      Error: Expected key descriptor but found "" in ""
          See https://github.com/testing-library/user-event/blob/master/README.md#keyboardtext-options
          for more information about how userEvent parses your input.
          at getNextKeyDef (C:\Projects\Templafy\UIComponents\node_modules\@testing-library\user-event\dist\keyboard\getNextKeyDef.js:26:11)
          at keyboardImplementation (C:\Projects\Templafy\UIComponents\node_modules\@testing-library\user-event\dist\keyboard\keyboardImplementation.js:35:40)
          at keyboardImplementationWrapper (C:\Projects\Templafy\UIComponents\node_modules\@testing-library\user-event\dist\keyboard\index.js:55:65)
          at typeImplementation (C:\Projects\Templafy\UIComponents\node_modules\@testing-library\user-event\dist\type\typeImplementation.js:49:51)
          at Object.type (C:\Projects\Templafy\UIComponents\node_modules\@testing-library\user-event\dist\type\index.js:27:60)  
          at Object.<anonymous> (C:\Projects\Templafy\UIComponents\src\lib\components\dateInput\DateInput.test.tsx:84:15)       
          at Promise.then.completed (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\utils.js:276:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\utils.js:216:10)
          at _callCircusTest (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\run.js:212:40)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at _runTest (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\run.js:149:3)
          at _runTestsForDescribeBlock (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\run.js:63:9)
          at _runTestsForDescribeBlock (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\run.js:57:9)
          at run (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\run.js:25:3)
          at runAndTransformResultsToJestFormat (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:176:21)
          at jestAdapter (C:\Projects\Templafy\UIComponents\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:109:19)
          at runTestInternal (C:\Projects\Templafy\UIComponents\node_modules\jest-runner\build\runTest.js:380:16)
          at runTest (C:\Projects\Templafy\UIComponents\node_modules\jest-runner\build\runTest.js:472:34)
          at Object.worker (C:\Projects\Templafy\UIComponents\node_modules\jest-runner\build\testWorker.js:133:12)

```

Problem description:
The error in the console is unexpected and confusing. 

Suggested solution:
The error should not appear. If the usage is not correct, we might need to update the documentation to make it clearer how this scenario with the Escape key could be tested.

**Comment by ph-fritsche** [comment]
Thanks for the report, but I could not reproduce this [in codesandbox](https://codesandbox.io/s/user-event-issue-689-pnnls?file=/src/issue-689.test.js).

The error you're seeing is currently to be expected when passing an empty string to `userEvent.keyboard`.
No idea why `userEvent.keyboard` receives an empty string in your setup.

If you can create a reproducible example, I'll gladly reopen, but for now there is nothing I can do.
