### ISSUE TITLE
When I run the tests together they break, but when I run them one by one they work normally

### ISSUE THREAD

**Issue by marcosapj2** [testing-library/user-event#798]
- `@testing-library/user-event` version: 12.8.3

- Testing Framework and version: Jest 26.6.0
  
- DOM Environment: JSDOM 16.7.0
  

Relevant code or config

```javascript
import PokemonList from '../'
import { render, screen, waitFor } from '@test-utils'
import { setupServer } from 'msw/node'
import userEvent from '@testing-library/user-event'
import listPokemonHandler from '@mocks/handlers/listPokemons'
import pokemonsMock from '@mocks/objects/pokemons.json'

describe('PokemonList', () => {
  const server = setupServer(listPokemonHandler)

  beforeAll(() => {
    server.listen()
  })

  afterEach(() => server.resetHandlers())
  afterAll(() => server.close())

  it('should change items when search', async () => {
    render(<PokemonList />)

    const input = screen.getByRole('textbox')

    userEvent.type(input, 'per') // This event is being fired in the test below

    await waitFor(() => {
      expect(screen.queryByText('Peraxoq')).toBeInTheDocument()
      expect(screen.queryByText('Peris')).toBeInTheDocument()
      expect(screen.queryByText('Pikalu')).not.toBeInTheDocument()
    })
  })

  it('should render the list of pokemons', async () => { // The two tests when I run them separately using `it.only` it works
    render(<PokemonList />) // Here I should have a list of 6 items, but I'm getting the result of a search with the text 'per'

    const lastPokemonOnFirstPage = pokemonsMock.results[5]

    await waitFor(() => {
      expect(screen.queryByText(lastPokemonOnFirstPage.name)).toBeInTheDocument()
    })
  })
})

```

What you did:
`react-app-rewired test PokemonList`
What happened:
<details>
  <summary>The tests are breaking, bringing the following feedback:</summary>

  ```javascript
 FAIL  src/containers/PokemonList/__tests__/PokemonList.test.tsx (8.03 s)
  PokemonList
    √ should change items when search (741 ms)
    × should render the list of pokemons (1041 ms)

  ● PokemonList › should render the list of pokemons

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

    <html>
      <head>
        <style
          data-styled="active"
          data-styled-version="5.3.3"
        >
          .ipWPMS{width:180px;height:180px;}
          .dlaHxw{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;width:NaNpx;}
          .hEsfMK{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;width:780px;}
          .kDlkLX{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:100%;width:100%;overflow-y:scroll;}
          .jwizbY{border-radius:10px;border:none;height:28px;outline:none;padding:0 10px;box-shadow:0 0 5px 0.5px rgba(0,0,0,0.1);}
          .fVjEJA.MuiListItem-root{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;background:#FFFFFF;margin:10px;border-radius:20px;width:240px;height:240px;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;box-shadow:0 0 5px 0.5px rgba(0,0,0,0.1);}
          .hCWYbA{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;font-family:'Flexo-Medium';}
          .duoVeC{width:400px;margin-bottom:20px;background-color:#FFFFFF;}
          @media (max-width:700px){.duoVeC{width:100%;}}
          .eMgrpW{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;width:100%;height:-webkit-min-content;height:-moz-min-content;height:min-content;}
          .dTHjxC{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;font-family:'Pokemon';color:white;font-size:40px;}
        </style>
        <style
          data-jss=""
          data-meta="MuiList"
        >

    .MuiList-root {
      margin: 0;
      padding: 0;
      position: relative;
      list-style: none;
    }
    .MuiList-padding {
      padding-top: 8px;
      padding-bottom: 8px;
    }
    .MuiList-subheader {
      padding-top: 0;
    }

        </style>
        <style
          data-jss=""
          data-meta="MuiListItem"
        >

    .MuiListItem-root {
      width: 100%;
      display: flex;
      position: relative;
      box-sizing: border-box;
      text-align: left;
      align-items: center;
      padding-top: 8px;
      padding-bottom: 8px;
      justify-content: flex-start;
      text-decoration: none;
    }
    .MuiListItem-root.Mui-focusVisible {
      background-color: rgba(0, 0, 0, 0.08);
    }
    .MuiListItem-root.Mui-selected, .MuiListItem-root.Mui-selected:hover {
      background-color: rgba(0, 0, 0, 0.08);
    }
    .MuiListItem-root.Mui-disabled {
      opacity: 0.5;
    }
    .MuiListItem-container {
      position: relative;
    }
    .MuiListItem-dense {
      padding-top: 4px;
      padding-bottom: 4px;
    }
    .MuiListItem-alignItemsFlexStart {
      align-items: flex-start;
    }
    .MuiListItem-divider {
      border-bottom: 1px solid rgba(0, 0, 0, 0.12);
      background-clip: padding-box;
    }
    .MuiListItem-gutters {
      padding-left: 16px;
      padding-right: 16px;
    }
    .MuiListItem-button {
      transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;
    }
    .MuiListItem-button:hover {
      text-decoration: none;
      background-color: rgba(0, 0, 0, 0.04);
    }
    @media (hover: none) {
      .MuiListItem-button:hover {
        background-color: transparent;
      }
    }
    .MuiListItem-secondaryAction {
      padding-right: 48px;
    }

        </style>
      </head>
      <body>
        <div>
          <section
            class="sc-dkPtRN kDlkLX"
            role="feed"
          >
            <ul
              class="MuiList-root sc-gsDKAQ hEsfMK MuiList-padding"
            >
              <div
                class="sc-kDTinF eMgrpW"
              >
                <h1
                  class="sc-iqseJM dTHjxC"
                >
                  VR Pokedex
                </h1>
                <input
                  class="sc-hKwDye sc-pVTFL jwizbY duoVeC"
                />
              </div>
              <li
                class="MuiListItem-root sc-iCfMLu fVjEJA MuiListItem-gutters"
              >
                <img
                  alt="Peris"
                  class="sc-bdvvtL ipWPMS"
                  height="180px"
                  src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5011.png"
                  width="180px"
                />
                <h2
                  class="sc-furwcr hCWYbA"
                >
                  Peris
                </h2>
              </li>
              <li
                class="MuiListItem-root sc-iCfMLu fVjEJA MuiListItem-gutters"
              >
                <img
                  alt="Peraxoq"
                  class="sc-bdvvtL ipWPMS"
                  height="180px"
                  src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5012.png"
                  width="180px"
                />
                <h2
                  class="sc-furwcr hCWYbA"
                >
                  Peraxoq
                </h2>
              </li>
            </ul>
          </section>
        </div>
      </body>
    </html>

      36 |
      37 |     await waitFor(() => {
    > 38 |       expect(screen.queryByText(lastPokemonOnFirstPage.name)).toBeInTheDocument()
         |                                                               ^
      39 |     })
      40 |   })
      41 | })

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:342:30)
      at Object.toBeInTheDocument (node_modules/expect/build/index.js:343:15)
      at src/containers/PokemonList/__tests__/PokemonList.test.tsx:38:63
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:51:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:127:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:119:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)  
```
  
</details>

Reproduction repository:
https://github.com/marcosapj2/vrpokedex

Problem description:
When I run the tests together they break, but when I run them one by one they work normally. What is happening is that the "userEvent.type(input, 'per')" shown above is somehow affecting the other test, causing the request return wrong

Suggested solution:
I don't know yet, I thought the cleanup would help but it already happens automatically

**Comment by marcosapj2** [comment]
The print of the tests running separately:
![image](https://user-images.githubusercontent.com/44703620/144722450-200db004-f8bd-4aa1-a95c-5504a1fe5984.png)
![image](https://user-images.githubusercontent.com/44703620/144722502-09917357-b506-4377-a8ad-954acd3a44ae.png)

**Comment by ph-fritsche** [comment]
You're global state change per `react-redux` is bleeding into the other test.
This is either because you don't reset it properly or because your debounced state changes happen during the next test.
