### ISSUE TITLE
Click on a checkbox generate a Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by GabrielBarcelos1** [testing-library/user-event#848]
- `@testing-library/user-event` version: `14.0.0-beta.9`

- Testing Framework and version: @testing-library / `13.0.0-alpha.5`
  
- DOM Environment: `27.5.0`
  

What you did: I just need to click on a `checkBox`

What happened: When I click on `checkBox` my test stops and returns:
```javascript
    RangeError: Maximum call stack size exceeded

      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLInputElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:205:9)
      at HTMLInputElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLInputElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at dispatchEvent (node_modules/@testing-library/user-event/dist/index.cjs:1420:12)
      at isElementType.type (node_modules/@testing-library/user-event/dist/index.cjs:1393:7)
      at dispatchEvent (node_modules/@testing-library/user-event/dist/index.cjs:1422:7)
      at isElementType.type (node_modules/@testing-library/user-event/dist/index.cjs:1393:7)
      at dispatchEvent (node_modules/@testing-library/user-event/dist/index.cjs:1422:7)
```

Problem description: after this PR https://github.com/testing-library/user-event/pull/847, click on a checkbox generate a `Maximum call stack size exceeded` error

**Comment by ph-fritsche** [comment]
Works as expected in codesandbox:
https://codesandbox.io/s/userevent-pr-template-forked-k8sl1?file=/src/App.test.js

Could your please provide more information about the test and the component under test?

> * Testing Framework and version: @testing-library / `13.0.0-alpha.5`

I guess this means `@testing-library/react@13.0.0-alpha.5`

> * DOM Environment: `27.5.0`

Is this `jest+jsdom`?

**Comment by ph-fritsche** [comment]
The loop is a result of the control being nested inside `<label>`. PR with a fix coming soon.
